"""just a test autogenerate3

Revision ID: 2f9241aa62fe
Revises: 762c271ca0a9
Create Date: 2018-05-12 02:02:37.933186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9241aa62fe'
down_revision = '762c271ca0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
