"""just a test autogenerate4

Revision ID: 5daed05122d6
Revises: 2f9241aa62fe
Create Date: 2018-05-12 02:05:38.177560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5daed05122d6'
down_revision = '2f9241aa62fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
