"""just a test autogenerate2

Revision ID: 762c271ca0a9
Revises: 0620904751ad
Create Date: 2018-05-12 02:02:12.605579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762c271ca0a9'
down_revision = '0620904751ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
