"""Added open high low to MarketData Tables

Revision ID: aa624fbed569
Revises: 111c44f28504
Create Date: 2018-05-29 15:30:38.708072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa624fbed569'
down_revision = '111c44f28504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MarketData_CASH_EUR_CHF_IDEALPRO', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_CHF_IDEALPRO', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_CHF_IDEALPRO', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_CNH_IDEALPRO', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_CNH_IDEALPRO', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_CNH_IDEALPRO', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_GBP_IDEALPRO', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_GBP_IDEALPRO', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_GBP_IDEALPRO', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_JPY_IDEALPRO', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_JPY_IDEALPRO', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_JPY_IDEALPRO', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_RUB_IDEALPRO', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_RUB_IDEALPRO', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_RUB_IDEALPRO', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_USD_IDEALPRO', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_USD_IDEALPRO', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CASH_EUR_USD_IDEALPRO', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBCH20_CHF_SMART', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBCH20_CHF_SMART', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBCH20_CHF_SMART', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBDE30_EUR_SMART', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBDE30_EUR_SMART', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBDE30_EUR_SMART', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBEU50_EUR_SMART', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBEU50_EUR_SMART', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBEU50_EUR_SMART', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBFR40_EUR_SMART', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBFR40_EUR_SMART', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBFR40_EUR_SMART', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBGB100_GBP_SMART', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBGB100_GBP_SMART', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBGB100_GBP_SMART', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBHK50_HKD_SMART', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBHK50_HKD_SMART', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBHK50_HKD_SMART', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBJP225_JPY_SMART', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBJP225_JPY_SMART', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBJP225_JPY_SMART', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBUS30_USD_SMART', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBUS30_USD_SMART', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBUS30_USD_SMART', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBUS500_USD_SMART', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBUS500_USD_SMART', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('MarketData_CFD_IBUS500_USD_SMART', sa.Column('open', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MarketData_CFD_IBUS500_USD_SMART', 'open')
    op.drop_column('MarketData_CFD_IBUS500_USD_SMART', 'low')
    op.drop_column('MarketData_CFD_IBUS500_USD_SMART', 'high')
    op.drop_column('MarketData_CFD_IBUS30_USD_SMART', 'open')
    op.drop_column('MarketData_CFD_IBUS30_USD_SMART', 'low')
    op.drop_column('MarketData_CFD_IBUS30_USD_SMART', 'high')
    op.drop_column('MarketData_CFD_IBJP225_JPY_SMART', 'open')
    op.drop_column('MarketData_CFD_IBJP225_JPY_SMART', 'low')
    op.drop_column('MarketData_CFD_IBJP225_JPY_SMART', 'high')
    op.drop_column('MarketData_CFD_IBHK50_HKD_SMART', 'open')
    op.drop_column('MarketData_CFD_IBHK50_HKD_SMART', 'low')
    op.drop_column('MarketData_CFD_IBHK50_HKD_SMART', 'high')
    op.drop_column('MarketData_CFD_IBGB100_GBP_SMART', 'open')
    op.drop_column('MarketData_CFD_IBGB100_GBP_SMART', 'low')
    op.drop_column('MarketData_CFD_IBGB100_GBP_SMART', 'high')
    op.drop_column('MarketData_CFD_IBFR40_EUR_SMART', 'open')
    op.drop_column('MarketData_CFD_IBFR40_EUR_SMART', 'low')
    op.drop_column('MarketData_CFD_IBFR40_EUR_SMART', 'high')
    op.drop_column('MarketData_CFD_IBEU50_EUR_SMART', 'open')
    op.drop_column('MarketData_CFD_IBEU50_EUR_SMART', 'low')
    op.drop_column('MarketData_CFD_IBEU50_EUR_SMART', 'high')
    op.drop_column('MarketData_CFD_IBDE30_EUR_SMART', 'open')
    op.drop_column('MarketData_CFD_IBDE30_EUR_SMART', 'low')
    op.drop_column('MarketData_CFD_IBDE30_EUR_SMART', 'high')
    op.drop_column('MarketData_CFD_IBCH20_CHF_SMART', 'open')
    op.drop_column('MarketData_CFD_IBCH20_CHF_SMART', 'low')
    op.drop_column('MarketData_CFD_IBCH20_CHF_SMART', 'high')
    op.drop_column('MarketData_CASH_EUR_USD_IDEALPRO', 'open')
    op.drop_column('MarketData_CASH_EUR_USD_IDEALPRO', 'low')
    op.drop_column('MarketData_CASH_EUR_USD_IDEALPRO', 'high')
    op.drop_column('MarketData_CASH_EUR_RUB_IDEALPRO', 'open')
    op.drop_column('MarketData_CASH_EUR_RUB_IDEALPRO', 'low')
    op.drop_column('MarketData_CASH_EUR_RUB_IDEALPRO', 'high')
    op.drop_column('MarketData_CASH_EUR_JPY_IDEALPRO', 'open')
    op.drop_column('MarketData_CASH_EUR_JPY_IDEALPRO', 'low')
    op.drop_column('MarketData_CASH_EUR_JPY_IDEALPRO', 'high')
    op.drop_column('MarketData_CASH_EUR_GBP_IDEALPRO', 'open')
    op.drop_column('MarketData_CASH_EUR_GBP_IDEALPRO', 'low')
    op.drop_column('MarketData_CASH_EUR_GBP_IDEALPRO', 'high')
    op.drop_column('MarketData_CASH_EUR_CNH_IDEALPRO', 'open')
    op.drop_column('MarketData_CASH_EUR_CNH_IDEALPRO', 'low')
    op.drop_column('MarketData_CASH_EUR_CNH_IDEALPRO', 'high')
    op.drop_column('MarketData_CASH_EUR_CHF_IDEALPRO', 'open')
    op.drop_column('MarketData_CASH_EUR_CHF_IDEALPRO', 'low')
    op.drop_column('MarketData_CASH_EUR_CHF_IDEALPRO', 'high')
    # ### end Alembic commands ###
