"""just a test autogenerate5

Revision ID: f86cace7a0cd
Revises: 5daed05122d6
Create Date: 2018-05-12 02:06:42.207041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86cace7a0cd'
down_revision = '5daed05122d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
